new: transportation and employment  api
ItamarShDev/my-gov-in-action pull request #14
Opened 2024-12-26 10:13 UTC by ItamarShDev

- Transportation
  -  accidents
  - bike routes
  - electric cars
- employment
  -  minimum salary
  -  average salary

2024-12-27 15:20 UTC, yafimski requested changes

2024-12-27 15:20 UTC, yafimski commented on app/categories/employment/average-salary/contants.ts
> +	description: "Analysis of average salaries along the years in Israel",
Two important distinctions about chart titles:
- the app is geared towards hebrew speakers. Let's do it in hebrew in terms of UI ppl-facing texts.

- We don't need to repeat it 4 times. I think we could only do 1 of them, preferrably the one centered above the chart itself.
- The `chartLabel` isn't necessary unless there is more than one label.
- 
![image](https://github.com/user-attachments/assets/93763605-7bc6-454f-b6bb-794785408199)

2024-12-27 15:20 UTC, yafimski commented on app/categories/employment/average-salary/contants.ts
> +export const CHART = {
This const is in a local 'constants' file but I strongly prefer to keep all pure data in the mocks folder (there is a transportationData.mock.ts there that is empty but we should do it like that I think).
Otherwise we will have 20 'constants' files in 20 different folders, it's not easy to navigate.

2024-12-27 15:20 UTC, yafimski commented on app/categories/employment/average-salary/contants.ts
> +import { chartTypes } from "~/types/units";
We already have 'types' folder outside 'routes'... we don't need another types folder.
Please move `ChartResponse` to the types folder alongside `units.ts`

2024-12-27 15:20 UTC, yafimski commented on app/categories/employment/average-salary/index.ts
> +				labels: SALARIES.map((salary) => String(salary.year)),
You map salaries twice.

2024-12-27 15:20 UTC, yafimski commented on app/categories/employment/average-salary/index.ts
> +				Xunits: "NUM" as UnitType,
Why not import `unitsTypes` from `units.ts` and use code we already have..? 
I prefer we do `unitsTypes.NUM` than `"NUM" as UnitType`

2024-12-27 15:20 UTC, yafimski commented on app/categories/employment/average-salary/index.ts
> +				numberFormatting: "WHOLE",
Same here, you ignore existing types from `units.ts`...

2024-12-27 15:20 UTC, yafimski commented on app/categories/employment/average-salary/salaryData.ts
> +export const SALARIES = [
I don't see a good reason to make this `as const`, since it's simpler to understand as a more abstract k:v pairs object.
That way we don't need to specify the 'year' but only the number pairs and we determine their 'name' or their 'display name' later on as we are rending the UI related to them.

2024-12-27 15:20 UTC, yafimski commented on app/categories/employment/minimum-salary/salaryData.ts
> +	{ year: 1999, salary: 2628.79 },
a lot of years appear twice. If this is mock data please put it in the mocks folder and try to keep it making sense in terms of years.

2024-12-27 15:20 UTC, yafimski commented on app/categories/transportation/accidents/contants.ts
> +	subtitle: "Top 10 Cities with Highest Traffic Accidents",
Generally for the app logic, I think you are used to high-res data segmentation but in this case we should start from 'Total accidents per year' not 'total accidents by city'.. I think in terms of the philosophycal idea of "a country's KPIs" people will care less about specific cities and more about the status of the nation. It also makes it easier to understand and more approachable to everyone including non-top-10-city residents.

This comment is because the .doc doesn't specify 'by city' anywhere..

2024-12-27 15:20 UTC, yafimski commented on app/categories/transportation/accidents/index.ts
> +import { CHART } from "./contants";
Naming is not good.. 'chart' doesn't say anything specific, neither does 'contants' (which should be 'conStants' by the way).

2024-12-27 15:20 UTC, yafimski commented on app/categories/transportation/accidents/type.ts
> +	DEAD: z.number().optional(),
Is this gpt-generated..?
Let's try to keep our app not cryptic

2024-12-27 15:20 UTC, yafimski commented on app/categories/transportation/bike-routes/index.ts
> +			"AUTHORITY,TRAFAUTH,LENGTH_M,LASTCHANGE,OPEN_YEAR,RoadType,Usable",
Please instruct me on how to set up mock data so that you can 'go and get real data'.. right now you are getting data with a bunch of stuff we probably don't need. Here for example I think we need 'total bike routes' and 'year', that's it..

You are working in a void so it's understandable but I did not have time to finish my task of setting up some mock data per few example charts and then you already advanced with the solution :/

2024-12-27 15:20 UTC, yafimski commented on app/categories/transportation/index.ts
> +		const accidents = await getAccidents();
We probably need a better strategy for this, for example a single object that has categories as keys and an array of fun() as values so we can iterate by key and run PromiseAll on them or something like that.

2024-12-27 15:20 UTC, yafimski commented on app/routes/types/api.ts
> +	data: TypeChart[] | null;
`TypeChart` is a bad name. Let's not use "type" anywhere we don't absolutely have to. Worst case do 'ChartType' which means 'which type is this chart' vs. 'TypeChart' which means 'which chart of this type'

2024-12-27 15:37 UTC, ItamarShDev commented on app/categories/employment/average-salary/contants.ts
> +	description: "Analysis of average salaries along the years in Israel",
as far as i understand, title and subtitle are the. page titles. the fact they are the same here is because i wanted to let you decide what are the titles

2024-12-27 15:38 UTC, ItamarShDev commented on app/categories/employment/average-salary/contants.ts
> +export const CHART = {
This is not mock. its part of the api data.

2024-12-27 15:41 UTC, ItamarShDev commented on app/categories/employment/average-salary/contants.ts
> +import { chartTypes } from "~/types/units";
We can have unified types folder, or separate them by domains. 
By Domain will have shorter names and will make is part of a 'module', while general one feels more organized.

we can do what ever you like better, i dont mind

2024-12-27 15:42 UTC, ItamarShDev commented on app/categories/employment/average-salary/index.ts
> +				labels: SALARIES.map((salary) => String(salary.year)),
So what? I can do it in one loop, but given the fact it is a small fixed size array the difference is negligible for the readability costs.

2024-12-27 15:42 UTC, ItamarShDev commented on app/categories/employment/average-salary/index.ts
> +				Xunits: "NUM" as UnitType,
You are correct

2024-12-27 15:46 UTC, ItamarShDev commented on app/categories/employment/minimum-salary/salaryData.ts
> +	{ year: 1999, salary: 2628.79 },
this is the real data

2024-12-27 15:49 UTC, ItamarShDev commented on app/categories/employment/average-salary/salaryData.ts
> +export const SALARIES = [
as const help ts to understand it should not change and that this data is static, regarding pairs vs objects, its a matter of taste.
I think key names are more explicit and can prevent mistakes.

2024-12-27 15:52 UTC, ItamarShDev commented on app/categories/transportation/accidents/contants.ts
> +	subtitle: "Top 10 Cities with Highest Traffic Accidents",
this is the old api moved and cleaned. i did not change its data https://my-gov-in-action.onrender.com/transportation#accidents

2024-12-27 15:53 UTC, ItamarShDev commented on app/categories/transportation/accidents/index.ts
> +import { CHART } from "./contants";
what would you suggest for the chart name? maybe PAGE_METADATA?

2024-12-27 15:53 UTC, ItamarShDev commented on app/categories/transportation/accidents/type.ts
> +	DEAD: z.number().optional(),
No man, this is Zod,  a validation library. i take proud of writing my own code.

2024-12-27 15:56 UTC, ItamarShDev commented on app/categories/transportation/bike-routes/index.ts
> +			"AUTHORITY,TRAFAUTH,LENGTH_M,LASTCHANGE,OPEN_YEAR,RoadType,Usable",
This is just a filtering on the vast amount of data they give us.
We dont have `total bike routes` so i take the city and the length and in the API calculate them together. the year here is not reliable, i will search for other data source for yearly reports

this is just a quick implementation to see the direction

2024-12-27 15:57 UTC, ItamarShDev commented on app/categories/transportation/index.ts
> +		const accidents = await getAccidents();
sure,

2024-12-27 16:00 UTC, ItamarShDev commented on app/categories/transportation/index.ts
> +		const accidents = await getAccidents();
made one example tell what you think

2024-12-27 16:00 UTC, ItamarShDev commented on app/routes/types/api.ts
> +	data: TypeChart[] | null;
ChartType is a bad name because it iss used by our libraries.

2025-01-04 08:31 UTC, yafimski commented on app/categories/transportation/accidents/type.ts
@ItamarShDev 😆

2025-01-04 08:33 UTC, yafimski approved these changes

2025-01-04 08:34 UTC, yafimski commented on app/categories/employment/average-salary/contants.ts
> +	description: "Analysis of average salaries along the years in Israel",
yeah i'm just saying i realized we probably need only the one centered above the chart, for users it will be 'too much info' i think. so we can have the others optional.

2025-01-04 08:35 UTC, yafimski commented on app/categories/employment/average-salary/contants.ts
> +import { chartTypes } from "~/types/units";
for me it's easier when it's organized

2025-01-04 08:38 UTC, yafimski commented on app/categories/transportation/bike-routes/index.ts
> +			"AUTHORITY,TRAFAUTH,LENGTH_M,LASTCHANGE,OPEN_YEAR,RoadType,Usable",
I get all this, we will talk about it, but in general I don't think we should get, use, or write any data that doesn't make sense with our data schema. if it's year:num then we shouldn't have 'city' anywhere and we should put it manually from data you collect or get sources that are year:num.

2025-01-04 09:08 UTC, ItamarShDev commented on app/categories/employment/average-salary/contants.ts
> +	description: "Analysis of average salaries along the years in Israel",
That will be changed after the UI is ready. 

We can ignore parts of the api data and remove them later.

2025-01-04 09:08 UTC, ItamarShDev commented on app/categories/employment/average-salary/contants.ts
> +import { chartTypes } from "~/types/units";
Moved to the main type folder

2025-01-04 18:48 UTC, ItamarShDev commented on app/categories/employment/average-salary/index.ts
> +				labels: SALARIES.map((salary) => String(salary.year)),
fixed

2025-01-04 18:49 UTC, ItamarShDev commented on app/categories/transportation/bike-routes/index.ts
> +			"AUTHORITY,TRAFAUTH,LENGTH_M,LASTCHANGE,OPEN_YEAR,RoadType,Usable",
I am still searching for such data. seems hard to find (for me)

2025-01-04 18:50 UTC, ItamarShDev commented on app/routes/types/api.ts
> +	data: TypeChart[] | null;
renamed to ChartData

2025-01-04 18:52 UTC, ItamarShDev commented on app/categories/transportation/accidents/type.ts
removed

2025-01-04 19:30 UTC, yafimski approved these changes

2025-01-04 19:30 UTC, merged